djangostagram/djangostagram/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from user.views import RegisterView, LoginView, logout
from post.views import WriteView, TimelineList, PostDetail

urlpatterns = [
    path('', TimelineList.as_view(), name='timeline'),
    path('admin/', admin.site.urls),
    path('user/register/', RegisterView.as_view(), name='register'),
    path('user/login/', LoginView.as_view(), name='login'),
    path('user/logout/', logout, name='logout'),
    path('upload/', WriteView.as_view(), name='write'),
	path('post/<int:pk>/', PostDetail.as_view(), name='detailview'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangostagram/post/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        db_table = 'post_tag'
        verbose_name = '포스트_태그'
        verbose_name_plural = '포스트_태그'

    def __str__(self):
        return self.name


class Post(models.Model):
    dsuser = models.ForeignKey('user.Dsuser', on_delete=models.CASCADE, verbose_name='작성자')
    title = models.CharField(max_length=100, verbose_name='제목', null=True)
    content = models.TextField(verbose_name='내용', null=False)
    img_src = models.ImageField(verbose_name='이미지주소', upload_to="image")
    create_date = models.DateField(verbose_name='등록일', auto_now_add=True, null=False, blank=False)
    tags = models.ManyToManyField(Tag, verbose_name='태그', related_name='tagged')

    class Meta:
        db_table = 'post'
        verbose_name = '포스트'
        verbose_name_plural = '포스트'
        ordering = ('create_date',)

    def __str__(self):
        return str(self.title)

djangostagram/user/models.py
from django.db import models

# Create your models here.
class Dsuser(models.Model):
    id = models.CharField(verbose_name='아이디', primary_key=True, max_length=128, unique=True)
    email = models.EmailField(verbose_name='이메일', max_length=255, null=False, blank=False)
    password = models.CharField(verbose_name='패스워드', max_length=128, null=False, blank=False)
    create_date = models.DateField(verbose_name='등록일', auto_now_add=True, null=False, blank=False)

    class Meta:
        db_table = 'dsuser'
        verbose_name = '사용자'
        verbose_name_plural = '사용자'

    def __str__(self):
        return self.id

djangostagram/user/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from .models import Dsuser


class RegisterForm(forms.Form):
    id = forms.CharField(
        error_messages={
            'required': '모든 값을 입력해야 합니다.'
        },
        max_length=128,
        label='아이디'
    )
    email = forms.EmailField(
        error_messages={
            'required': '모든 값을 입력해야 합니다.'
        },
        max_length=255, label='이메일'
    )
    password = forms.CharField(
        error_messages={
            'required': '모든 값을 입력해야 합니다.'
        },
        max_length=128,
        widget=forms.PasswordInput, label='비밀번호'
    )
    re_password = forms.CharField(
        error_messages={
            'required': '모든 값을 입력해야 합니다.'
        },
        max_length=128,
        widget=forms.PasswordInput, label='비밀번호 확인'
    )

    def clean(self):
        cleaned_data = super().clean()
        id = cleaned_data.get('id')
        password = cleaned_data.get('password')
        re_password = cleaned_data.get('re_password')

        if password and re_password:
            if password != re_password:
                self.add_error('password', '비밀번호가 서로 다릅니다.')
                self.add_error('re_password', '비밀번호가 서로 다릅니다.')

        try:
            Dsuser.objects.get(id=id)
            self.add_error('id', '이미 가입된 아이디입니다.')
        except Dsuser.DoesNotExist:
            pass


class LoginForm(forms.Form):
    id = forms.CharField(
        error_messages={
            'required': '아이디를 입력해주세요.'
        },
        max_length=128,
        label='아이디'
    )
    password = forms.CharField(
        error_messages={
            'required': '비밀번호를 입력해주세요.'
        },
        widget=forms.PasswordInput, label='비밀번호'
    )

    def clean(self):
        cleaned_data = super().clean()
        id = cleaned_data.get('id')
        password = cleaned_data.get('password')

        if id and password:
            try:
                user = Dsuser.objects.get(id=id)
            except Dsuser.DoesNotExist:
                self.add_error('id', '등록된 아이디가 없습니다')
                return

            if not check_password(password, user.password):
                self.add_error('password', '비밀번호가 틀렸습니다')

djangostagram/post/views.py
from django.shortcuts import render
from .models import Post, Tag
from user.models import Dsuser
from .form import WriteForm
from user.views import login_required
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView
from django.utils.decorators import method_decorator


# Create your views here.
@method_decorator(login_required, name='dispatch')
class WriteView(FormView):
    template_name = 'write.html'
    form_class = WriteForm
    success_url = '/'

    def form_valid(self, form):
        tags = form.data.get('tags').split(',')

        arr_tag = []
        for tag in tags:
            tag = tag.strip()
            tag = Tag(name=tag)
            tag.save()

            arr_tag.append(tag)

        post = Post(
            dsuser=Dsuser.objects.get(id=self.request.session.get('user')),
            title=form.data.get('title'),
            content=form.data.get('content'),
            img_src=self.request.FILES['img_src']
        )
        post.save()

        for each_tag in arr_tag:
            post.tags.add(each_tag)

        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class TimelineList(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'timeline_list'
    paginate_by = 4

    def get_queryset(self, **kwargs):
        queryset = Post.objects.filter(dsuser=Dsuser.objects.get(id=self.request.session.get('user'))).order_by('-id')
        return queryset


@method_decorator(login_required, name='dispatch')
class PostDetail(DetailView):
    model = Post
    template_name = 'detail_view.html'
    context_object_name = 'post_detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        query_data = Post.objects.filter(id=self.kwargs['pk'], dsuser=Dsuser.objects.get(
            id=self.request.session.get('user'))).prefetch_related('tags')

        tags = query_data[0].tags.all()
        tag_name = ''
        for idx, tag in enumerate(tags):
            if str(tag) == '':
                continue

            tag_name += '#' + str(tag)

            if idx < len(tags) - 1:
                tag_name += ' '

        context['post_detail'] = query_data
        context['page'] = self.request.GET.get('page', 1)
        context['tags'] = tag_name

        return context

djangostagram/user/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic.edit import FormView
from .forms import RegisterForm, LoginForm
from .models import Dsuser
from django.contrib.auth.hashers import make_password


# Create your views here.
class RegisterView(FormView):
    template_name = 'register.html'
    form_class = RegisterForm
    success_url = '/'

    def form_valid(self, form):
        dsuser = Dsuser(
            id=form.data.get('id'),
            email=form.data.get('email'),
            password=make_password(form.data.get('password'))
        )
        dsuser.save()

        self.request.session['user'] = form.data.get('id')

        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        self.request.session['user'] = form.data.get('id')

        return super().form_valid(form)


def logout(request):
    if 'user' in request.session:
        del (request.session['user'])

    return redirect('/')


def login_required(function):
    def wrap(request, *args, **kwargs):
        user = request.session.get('user')
        if user is None or not user:
            return redirect('/user/login')
        return function(request, *args, **kwargs)

    return wrap

djangostagram/post/templates/detail_view.html
{% extends "base.html" %}
{% block contents %}

{% for detail in post_detail %}
<div class="card">
    <img src="../../media/{{ detail.img_src }}" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">{{ detail.title }}</h5>
      <p class="card-text">{{ detail.content }}</p>
      <p class="card-text">{{ tags }}</p>
      <p class="card-text">작성자: {{ detail.dsuser_id }}, 작성일: {{ detail.create_date }}</p>
      <a href="/?page={{ page }}" class="btn btn-primary">돌아가기</a>
    </div>
</div>
{% endfor %}

{% endblock %}

djangostagram/post/templates/index.html
{% extends "base.html" %}
{% block contents %}
{% for timeline in timeline_list %}
<div class="card">
    <img src="media/{{ timeline.img_src }}" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title">{{ timeline.title }}</h5>
      <p class="card-text">{{ timeline.content }}</p>
      <p class="card-text">작성자: {{ timeline.dsuser_id }}, 작성일: {{ timeline.create_date }}</p>
      {% if page_obj.number > 1 %}
      <a href="post/{{ timeline.id }}?page={{ page_obj.number }}" class="btn btn-primary">상세보기</a>
      {% else %}
      <a href="{% url 'detailview' pk=timeline.id %}" class="btn btn-primary">상세보기</a>
      {% endif %}
    </div>
</div>
{% endfor %}

<div class="row mt-2">
    <div class="col-12">
        <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">이전</a></li>
            {% endif %}
            <li class="page-item active"><span class="page-link">{{ page_obj.number }}/{{ paginator.num_pages }}</span></li>
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">다음</a></li>
            {% endif %}
        </ul>
        </nav>
    </div>
</div>
{% endblock %}

djangostagram/post/templates/write.html
{% extends "base.html" %}
{% block header %}
<script>
  function checkValue(){
    img_src = $('#id_img_src').val();
    content = $('#id_content').val();

    if (!img_src) {
      alert('이미지 주소는 입력 필수값 입니다.')
      return;
    } else if (!content) {
      alert('내용은 입력 필수값 입니다.')
      return;
    } else {
      $("form").submit();
    }
  }

  function cancle(){
    location.href='/';
  }
</script>
{% endblock %}

{% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>포스트 작성</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <form method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group mt-2">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% if field.field.widget.template_name == 'django/forms/widgets/textarea.html' %}
        <textarea class="form-control" id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}" rows="10"></textarea>
        {% else %}
          {% if field.field.widget.input_type == 'file' %}
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" accept="image/jpeg,image/png,image/bmp,image/gif"  />
          {% else %}
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
          placeholder="{{ field.label }}" name="{{ field.name }}"  />
          {% endif %} 
        {% endif %}
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
    </form>
    <div class="col-12 mt-2 text-center">
      <button class="btn btn-primary" onclick="checkValue()">저장</button>
      <button class="btn btn-primary" onclick="cancle()">취소</button>
    </div>
  </div>
</div>
{% endblock %}

djangostagram/user/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>장고스타그램</title>
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">

  {% block header %}
  {% endblock %}
</head>
<body>
    <div class= "container">
        <div>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <span class="navbar-brand px-3">Djangostagram</span>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'timeline'%}">타임라인</a>
                        </li>
                        {% if request.session.user %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">로그아웃</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'write'%}">글작성</a>
                        </li>
                        <li class="nav-item" >
                            <span class="nav-link">Hello, {{ request.session.user }}</span>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">회원가입</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login'%}">로그인</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        {% block contents %}
        {% endblock %}
    </div>
</body>
</html>

djangostagram/user/templates/login.html
{% extends "base.html" %}
{% block header %}
<script>
  function checkValue(){
    id = $('#id_id').val();
    pwd = $('#id_password').val();

    if (!id){
      alert('ID를 입력해 주세요.');
      return;
    } else if (!pwd) {
      alert('비밀번호를 입력해 주세요.');
      return;
    }
    else {
      $("form").submit();
    }
  }
</script>
{% endblock %}

{% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>로그인</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <form method="POST" action=".">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group mt-2">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
          placeholder="{{ field.label }}" name="{{ field.name }}" />
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
    </form>
    <div class="mt-2 text-center">
      <button class="btn btn-primary" onclick="checkValue()">로그인</button>
    </div>
  </div>
</div>
{% endblock %}

djangostagram/user/templates/register.html
{% extends "base.html" %}
{% block header %}
<script>
  function checkValue(){
    id = $('#id_id').val();
    email = $('#id_email').val();
    pwd = $('#id_password').val();
    re_pwd = $('#id_re_password').val();

    if (!id || !email || !pwd || !re_pwd){
      alert('모든 값을 입력해야 합니다.');
      return;
    } else if (pwd != re_pwd) {
      alert('비밀번호가 다릅니다.');
      return;
    }
    else {
      $("form").submit();
    }
  }
</script>
{% endblock %}

{% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>회원가입</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <form method="POST" action=".">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group mt-2">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
          placeholder="{{ field.label }}" name="{{ field.name }}" />
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
    </form>
  </div>
  <div class="col-12 mt-2 text-center">
    <button class="btn btn-primary" onclick="checkValue()">회원가입</button>
  </div>
</div>
{% endblock %}